name: event-calender-deployed
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: event-calender-deployed-settings
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        docker build -t calendarservice.api .
        docker tag calendarservice.api registry.heroku.com        
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
