name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is action
        with:
          heroku_api_key: ${{env.HEROKU_API_KEY}}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }} #Must be unique in Heroku
          heroku_email: ${{ env.HEROKU_EMAIL }}

          usedocker: true
